### ISSUE TITLE
add support for ssl3 since ssl 1.1 is eol 

### ISSUE THREAD

**Issue by gOOvER** [openmultiplayer/launcher#153]
and support for ssl3. ssl 1.1 is eol and should not be used anymore

**Comment by AmyrAhmady** [comment]
There are many distros that are not EOL but they do not ship libssl 3.x. in order to stay compatible with majority, we have to do this. In order to stay compatible with almost all samp hosting services, we have to do this.

If you have any issue installing 1.x versions, you can follow this guide:
https://askubuntu.com/questions/1403837/how-do-i-use-openssl-1-1-1-in-ubuntu-22-04

**Comment by Zorono** [comment]
Why not just add optional support for ssl3 (to be enabled as alternative for that ssl1.1 with a boolean variable) ???

**Comment by AmyrAhmady** [comment]
boolean variable where? it's not something you change at runtime, libssl is linked during build time

**Comment by Zorono** [comment]
> boolean variable where? it's not something you change at runtime, libssl is linked during build time

I didn't mean runtime of course 😒
